# Site settings
title: Portfolio
email: neel93@gmail.com
description: Personal Portfolio
baseurl: "/portfolio-blog"
twitter_username: Sanket
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Sanket Rai Choudhary" # Set default author name
      categories: "work"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
