# Site settings
title: Blog
email: tpriya_singh@ymail.com
description: Personal Portfolio
baseurl: "/portfolio-blog"
twitter_username: 
   
linkedin_username: tpriya_singh@ymail.com

avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Tarupriya Singh" # Set default author name
      categories: "work"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
