# Site settings
title: Blog
email: tpriya_singh@yahoo.in
description: Personal Portfolio
baseurl: "/portfolio-blog"

avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Taru Priya Singh" # Set default author name
      categories: "work"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
